### ISSUE TITLE
Doc building CI ran on my fork ...

### ISSUE THREAD

**Issue by cooperlees** [terragraph/meta-terragraph#16]
### Prerequisites

- [X] I have read the [Contributing Guidelines](../blob/main/CONTRIBUTING.md).
- [X] I have read the [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md).

### Category

Documentation

### Priority

Low

### Description

It seems docs built and uploaded from my fork - Is this wanted?

https://github.com/cooperlees/meta-terragraph/runs/7400340300?check_suite_focus=true

### Steps to reproduce

Fork the repo and push a commit to trigger CI.

### Additional information (logs, etc.)

https://github.com/cooperlees/meta-terragraph/runs/7400340300?check_suite_focus=true

### Your environment

- Software version: l33t version
- Firmware version: Super l33t version
- Hardware: GitHub Actions instance.

### External tickets

69

**Comment by elludraon** [comment]
I have no strong opinion either way, though I think GitHub prompts you to enable Actions on your fork?

It looks like we could disable specific workflows/jobs by adding:
```yaml
jobs:
  xx:
    if: github.repository == 'terragraph/meta-terragraph'
```

**Comment by cooperlees** [comment]
I'm most concerned about the "Deploy to GitHub Pages" step and it passing ... What's it deploying and where?

<img width="563" alt="Screen Shot 2022-07-18 at 7 38 50 PM" src="https://user-images.githubusercontent.com/3005596/179652485-cb8f8ece-6c18-495d-b7e5-d4f326a8333b.png">

**Comment by MatthewWEdwards** [comment]
The workflow writes to the `gh-pages` branch in your forked repo. If GitHub pages were enabled, then the website would be available at https://cooperlees.github.io/meta-terragraph. This URL 404s because GitHub pages are not enabled for your fork.

**Comment by cooperlees** [comment]
Ahh ok. I don't think we should dump that into people's GitHub pages. So maybe we just add Jeffrey's suggestion + allow people to remove it if they do want that for testing in their personal forks.

p.s. It's very sad that terragraph.com is IPv4 only :(.

**Comment by elludraon** [comment]
I think we'll just leave it like this given that a user needs to enable *both* GitHub Actions and GitHub Pages manually, so there are probably no surprises. I still don't see any clear reason to go either way, so might as well save some code.
