### ISSUE TITLE
platform_linux fails to program routes using netlink after e2e_minion restarts

### ISSUE THREAD

**Issue by c0D3M** [terragraph/meta-terragraph#35]
### Prerequisites

- [X] I have read the [Contributing Guidelines](../blob/main/CONTRIBUTING.md).
- [X] I have read the [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md).

### Category

Routing (ex. Open/R, VPP, BGP)

### Priority

High

### Description

Seeing an issue in **fib_linux** , once system boot ,  default route are programmed and node onboard.
Restart **e2e_minion** now,  node can't onboard (default route get deleted and is not re-programmed next time), upon investigation 
Error is seen in **openr** log,
```
I0904 17:22:11.684891 22056 Fib.cpp:582] Adding/Updating 5 unicast routes in FIB
E0904 13:47:22.512974 22056 Fib.cpp:603] Failed to add/update unicast routes in FIB. Error: apache::thrift::TApplicationException: openr::fbnl::NlException: Error(19) - No such device. One or more netlink request failed
```
Simulatenous error is seen in **fib_linux** log,
```
I0904 17:23:13.605388 24895 NetlinkFibHandler.cpp:105] Adding/Updating unicast routes of client OPENR, numRoutes=5
E0904 17:23:13.609419 24882 NetlinkProtocolSocket.cpp:171] Netlink request error for seq=350, retval=-19
E0904 17:23:13.610333 24882 NetlinkProtocolSocket.cpp:171] Netlink request error for seq=352, retval=-19
E0904 17:23:13.611045 24882 NetlinkProtocolSocket.cpp:171] Netlink request error for seq=354, retval=-19
E0904 17:23:13.611716 24882 NetlinkProtocolSocket.cpp:171] Netlink request error for seq=356, retval=-19
E0904 17:23:13.612370 24882 NetlinkProtocolSocket.cpp:171] Netlink request error for seq=358, retval=-19
```

restarting fib_linux fixes the issues.
This same scenario works fine with fib_vpp.

### Steps to reproduce

1. Start the node and let it onboard to e2e_controller.
2. Now restart e2e_minion

### Additional information (logs, etc.)

**openr**
```
I0904 17:22:11.684891 22056 Fib.cpp:582] Adding/Updating 5 unicast routes in FIB
E0904 13:47:22.512974 22056 Fib.cpp:603] Failed to add/update unicast routes in FIB. Error: apache::thrift::TApplicationException: openr::fbnl::NlException: Error(19) - No such device. One or more netlink request failed
```

**fib_linux**
```
I0904 17:23:13.605388 24895 NetlinkFibHandler.cpp:105] Adding/Updating unicast routes of client OPENR, numRoutes=5
E0904 17:23:13.609419 24882 NetlinkProtocolSocket.cpp:171] Netlink request error for seq=350, retval=-19
E0904 17:23:13.610333 24882 NetlinkProtocolSocket.cpp:171] Netlink request error for seq=352, retval=-19
E0904 17:23:13.611045 24882 NetlinkProtocolSocket.cpp:171] Netlink request error for seq=354, retval=-19
E0904 17:23:13.611716 24882 NetlinkProtocolSocket.cpp:171] Netlink request error for seq=356, retval=-19
E0904 17:23:13.612370 24882 NetlinkProtocolSocket.cpp:171] Netlink request error for seq=358, retval=-19
```

### Your environment

- Software version: M80 with latest changes picked.
- Firmware version:
- Hardware:

**Comment by MatthewWEdwards** [comment]
How is e2e-minion being restarted? Is the program restarted by logging-in to the node and issuing the `sv restart e2e-minion` command, or is e2e-minion restarted after a [node configuration update](https://terragraph.com/docs/developer/Configuration_Management#post-config-actions)?

If minion is restarted after a node configuration update triggers a `RESTART_MINION` action, you can try to modify minion to restart fib_linux systematically. See [this portion](https://github.com/terragraph/meta-terragraph/blob/main/src/terragraph-e2e/e2e/minion/ConfigApp.cpp#L345) of the minion source

**Comment by MatthewWEdwards** [comment]
retval=-19 in the fib_linux log correspond to NLE_NOADDR error (https://www.infradead.org/~tgr/libnl/doc/api/error_8c_source.html)

Can you monitor the link-local addresses on the node before during and after you restart e2e-minion?

**Comment by c0D3M** [comment]
Thanks Matthew,
Yes minion is started using ```sv restart e2e_minio```

**Comment by c0D3M** [comment]
Do you link-local of terra0 , if yes , then i did a watch of interface during sv restart of e2e_minion
terra0 disapper first
re-appear without ipv6 link-local
then ip6 link-local comes on terra0 interface 

still fib_linux/openr couldnt recover and no def gw is set.

**Comment by MatthewWEdwards** [comment]
Can you post the node configuration you're using as well?

**Comment by MatthewWEdwards** [comment]
Copy-pasting some direct messages:

>Here is the accompanying Open/R documentation relating to your issue: https://openr.readthedocs.io/Protocol_Guide/Platform.html

> My suspicion is that when you bring down e2e-minion, the terraX interfaces are also brought down, but there is a delay between when Open/R receives notifications about those interfaces going down.

> Then, when Open/R requests the fib_linux programs routes, it asks the fib to program routes for interfaces which don't exist, hence the errors you see

> When the interfaces go down, notifications should be passed as represented by the bidirectional arrows on the right side of this diagram

![image](https://user-images.githubusercontent.com/19556631/189389277-00973584-f990-422d-9537-a199acbd9784.png)

> I don't believe we observe the same issues you're experiencing on our platform, and I don't think we'll be able to debug it absent your platform. Let me know if you need any more guidance debugging this

**Comment by MatthewWEdwards** [comment]
[c0D3M](https://github.com/c0D3M) Debugged this issue. They will submit a PR shortly. Copy-pasting some messages from our direct messages:

---


Hi , So I compiled nlmon.ko to packet capture netlink message, got it and now i see real problem, interface index of terra0 is older !,  after minion restart terra0 is recreated with new interface index but platform_linux send message to older interface index which doesnt exist (thats why we see NODEV error in netlink also) , and when we restart fib_linux it get new interface index of terra0 and everything works afterward, so now the q is how platform_linux get update interface index of terra0, does it store in some variable ? I see this 
```
 NetlinkFibHandler::getIfIndex
 ```
 , shd platform_linux update its cache if interface goes down , may be platform_linux shd listen on netlink event , old code there is no cache thing in 
 ```
NetlinkFibHandler.h
```
  and buildNextHop uses entirely differently way , something like  create address and then getIfIndex , thats why old code works everytime

**Comment by MatthewWEdwards** [comment]
In summary: `openr` sends `platform_linux` requests to program routes in Linux targeting interface indices which no-longer exist after `e2e-minion` is restarted. `openr` will not attempt to re-program the routes after the netlink errors. Restarting `fib_linux` will cause `openr` to attempt to program routes again, hence the existing workaround being to restart `fib_linux`

[c0D3M](https://github.com/c0D3M) has fixed this issue by checking if the interface index `platform_linux` attempts to program routes for exists, and if it doesn't then `platform_linux` won't program the route. We may also want to upstream this fix to Open/R itself.

**Comment by c0D3M** [comment]
> [c0D3M](https://github.com/c0D3M) has fixed this issue by checking if the interface index `platform_linux` attempts to program routes for exists, and if it doesn't then `platform_linux` won't program the route. We may also want to upstream this fix to Open/R itself.

Fix is if the interface doesn't exists , cache will re-initialized so that further netlink request succeed.
