### ISSUE TITLE
Array support in configuration files

### ISSUE THREAD

**Issue by klausneda** [terragraph/meta-terragraph#52]
### Prerequisites

- [X] I have read the [Contributing Guidelines](../blob/main/CONTRIBUTING.md).
- [X] I have read the [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md).

### Question

Hello.

Could you provide additional details about the difficulty in supporting arrays in the configuration file? I understand the issues resides when generating the initial configuration from the configuration layers.

Thank you.

**Comment by elludraon** [comment]
Hi - the main issue with arrays is that layering by regular JSON merge will not handle arrays logically, and we did not think that adding special array support would have benefits outweighing the confusion. We generally used CSV strings in place of arrays.

Sorry for the late reply, please feel free to re-open if you have further questions/comments.
